menu:
    Accueil: /
    Archives: archives/
    Feed: atom.xml

favicon: logo.png
logo: logo.png

# Comment
# e.g disqus: claymcleod 
disqus:

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2023

# Image Credits
enable_image_credit: true 
